### ISSUE TITLE
Document how to proceed with manual deduplication / export keep_one_unique_citation?

### ISSUE THREAD

**Issue by LukasWallrich** [camaradesuk/ASySD#11]
Currently, I get confused what to do after I have subset the `manual_dedup` dataset. I can see the `dedup_citations_add_manual` function, but that seems to rerun the entire automatic deduplication again as well ... is there any reason to do that? I would have expected to just call something like the `keep_one_unique_citation` ... but I am not sure.

Could you maybe add an example of that to the README? And possibly export the `keep_one_unique_citation` function, or clarify the documentation of `dedup_citations_add_manual` ... maybe you could also add an option there to skip the automatic deduplication step?

**Comment by kaitlynhair** [comment]
I have added a vignette to describe the manual dedup process here https://camaradesuk.github.io/ASySD/articles/basic-deduplication.html. 

I agree that rerunning the entire process again isn't optimal and takes time. Will aim to improve this function in future
