### ISSUE TITLE
Provide progress update

### ISSUE THREAD

**Issue by LukasWallrich** [camaradesuk/ASySD#16]
Related to https://github.com/ESHackathon/CiteSource/issues/26, it would be great if ASySD could provide progress updates, e.g., through the progressr package - otherwise, users have no idea how long the deduplication is likely to take (or whether it even is still running) ...

**Comment by kaitlynhair** [comment]
ASySD now provides messages with the stage of deduplication. This is also implemented in the latest version of the shiny app (like CiteSource!)
