### ISSUE TITLE
Parallel processing issues - "all scheduled cores encountered errors" and avoid detect_cores()

### ISSUE THREAD

**Issue by LukasWallrich** [camaradesuk/ASySD#17]
See https://github.com/ESHackathon/CiteSource/issues/54 - should be resolved here.

**Comment by kaitlynhair** [comment]
This happens when fields are missing - have now suppressed this message.

**Comment by LukasWallrich** [comment]
Great that you tracked it down. However, suppressing all warnings might be risky in terms of hiding future issues. Is it worth just suppressing this warning - e.g., by adopting this function?

https://rdrr.io/github/jbullock35/Bullock/src/R/suppress_warnings.R
