### ISSUE TITLE
Remove dplyr::funs to avoid warning

### ISSUE THREAD

**Issue by LukasWallrich** [camaradesuk/ASySD#2]
When merging records, dplyr gives a warning: 

```
Warning message:
`funs()` was deprecated in dplyr 0.8.0.
```

I think that can be fixed by just replacing `funs` by `~` in `merge_metadata`

**Comment by kaitlynhair** [comment]
Thanks for flagging this - I have replaced with lst() which works the same way.

**Comment by kaitlynhair** [comment]
In certain situations (character(0)) I am finding that lst() causes an error so have now replaced with ~ as you suggested!
