### ISSUE TITLE
Error in flow of dedup_citations_add_manual - fails to deduplicate?

### ISSUE THREAD

**Issue by LukasWallrich** [camaradesuk/ASySD#22]
I am running into errors with manual deduplication on the Shiny app, in that sometimes nothing happens - I believe that is because any run where the record_id needs to be fixed skips all other processing of the citations - the final `else` appears misplaced? Am I getting that wrong?

**Comment by LukasWallrich** [comment]
Actually, it makes sense for ASySD to struggle with invalid record_ids here, as the additions include record_ids ... though there should probably be an informative error (or - more efficiently - the option to pass ASySD output rather than the raw input?)

In CiteSource Shiny, where the issue arose, I now fixed it by creating valid record_ids (instead of drawing them from potentially duplicated `ID`s) before deduplicating, so this issue no longer holds us up there.

**Comment by kaitlynhair** [comment]
Hi Lukas, 
Can you confirm whether this is still an issue? I was struggling to replicate it but I've also just updated the app with a few other features. If you still have this problem, could you maybe attach your data and I can look into it?

**Comment by LukasWallrich** [comment]
As said in my last comment, I fixed it in the CiteSource app - so the issue does not appear there anymore. I still proposed a change to ASySD above, but can't remember the details - so if the second comment does not make sense to you, feel free to close this :)
