### ISSUE TITLE
Set shiny_progress option in dedup_citations automatically

### ISSUE THREAD

**Issue by LukasWallrich** [camaradesuk/ASySD#23]
Hi there - I was just reading ?dedup_citations and noticed the `shiny_progress` option - given that this should never be set outside a Shiny app, could this be replaced by the following line in the function? That would simplify the user interface.

```r
if (find.package("shiny") != character(0)) {
   shiny_progress <- shiny::isRunning()
} else {
  shiny_progress <- FALSE
}
```

**Comment by kaitlynhair** [comment]
Great suggestion! Now added to latest version
