### ISSUE TITLE
dedup_citations_add_manual fails when sources (or labels) initially include commas

### ISSUE THREAD

**Issue by LukasWallrich** [camaradesuk/ASySD#30]
I just ran into another issue (soon done with deduplication for now, so this stream will end :)) - when sources contain commas, it becomes impossible to use `dedup_citations_add_manual` because `tidyr::separate_rows` will fail. 

You might want to reject (or replace) such commas in the original input but failure so late down the line (after manual review) is frustrating. In this case, I am not quite sure why you unmerge the duplicates in any case, rather than just merging them with the additional citations - so there might be a way to simplify that function?

```r
tibble::tribble(
  ~record_ids,     ~label,              ~source,                                                                
   "10099, 17620",  "unknown, unknown",  "references_ID_43611.pdf, references_38862.pdf, references_38862.pdf"
) %>% tidyr::separate_rows(record_ids, source, label, sep = ", ")

```

**Comment by LukasWallrich** [comment]
(In my case, this "source" was the result of multiple deduplication runs in a row - which would not seem to be a rare use case, if you update a search ...)

**Comment by kaitlynhair** [comment]
I believe this issue is now resolved in the latest version
