### ISSUE TITLE
Add Shiny interface for manual dedup?

### ISSUE THREAD

**Issue by LukasWallrich** [camaradesuk/ASySD#41]
When I use `ASySD`, I am very happy using R code - except for the step of reviewing potential manual duplicates. That can obviously happen outside R, but I prefer a Shiny interface - and created one for my own use based on [revtools](https://github.com/mjwestgate/revtools) code.

You can find that code in [this gist](https://gist.github.com/LukasWallrich/7d75a4211c0bc3816faef2f09b28a0b8). To use it, a user can then just run the following code (and the rename step could obviously be dropped if the code was properly aligned with ASySD).

The original code is GPL-3, so can be adapted for ASySD. If this is of interest but you are pressed for time, I'd be happy to create a PR - just let me know :)

```r
source("manual_dedup.R")

hits_dedup$manual_dedup <- hits_dedup$manual_dedup %>%
  rename_with(~ str_replace(.x, "1$", "_1")) %>%
  rename_with(~ str_replace(.x, "2$", "_2")) %>%
  manual_dedup()
```

**Comment by kaitlynhair** [comment]
This is great Lukas - been an issue I've been meaning to work on for a longggg time. 

If you have time, I'd love if you could create a PR for this.

**Comment by tayates** [comment]
This looks like exactly what I need, many thanks Lukas and Kaitlyn. I am a STATA user, straying into R to use this useful package. With 60MB of .csv files to deduplicate, I don't think I can use the full Shiny interface (when I try to upload data, it disconnects from the server). Is there an adaptation to the standard code that I can use to upload 10 .csv files (exported from Zotero, then columns renamed so fields are recognised by ASySD), autodeduplicate, complete the remaining manual deduplication via the ShinyApp, then export the deduplicated records in a standard format?

**Comment by LukasWallrich** [comment]
@tayates note that ASySD directly support Zotero csv s if you import them with method = "zotero_csv"

**Comment by kaitlynhair** [comment]
Closing as now integrated into the package! Thanks @LukasWallrich :-)
