### ISSUE TITLE
DOI prefix not being stripped and effecting true pair identification

### ISSUE THREAD

**Issue by TRileyNOAA** [camaradesuk/ASySD#55]
CiteSource user ran into this and I was surprised as I knew there was a script to strip prefixes in ASySD. It appears that this is not happening. I can see the prefix in the unique citations post-dedup, which causes these records to not be identified, auto or for manual review.

When stopping the DOI prefix with find/replace in EndNote and testing these, CiteSource/ASySD catches everything.

**Comment by LukasWallrich** [comment]
To clarify, this works in the current ASySD version

**Comment by LukasWallrich** [comment]
Not an issue regarding DOIs - but regarding medline imports where synthesisr failed

**Comment by TNRiley** [comment]
@kaitlynhair you can close this!
