### ISSUE TITLE
Bad field for this Reference Type -- ISBN

### ISSUE THREAD

**Issue by Kirsten-Ziesemer** [camaradesuk/ASySD#6]
Hi Kaitlyn, I have been playing around with the update of ASYSD and get the following error: Bad field for this Reference Type -- ISBN. It seems that the field-name should be: ISBN/ISSN. Would it be possible to change this (this for the write.citations(type="endnote-tab")? Thanks in advance!

**Comment by kaitlynhair** [comment]
Hi Kristen, 

I think I have fixed this in the latest commit. Note that the latest version of write_citations has the argument type="txt" instead of endnote-tab. Please let me know if it now works OK for you!
