### ISSUE TITLE
Document required fields and/or rethink requirements

### ISSUE THREAD

**Issue by LukasWallrich** [camaradesuk/ASySD#9]
Currently ASySD fails if one of the following fields are missing:

`select(author, title, year, journal, abstract, doi, number, pages, volume, isbn, record_id, label, source)`

It would be great to document which fields are required and to throw a clearer error message when required fields are missing ... and possible you could also automatically add some missing fields (setting them to NA) - e.g. ISBN?

**Comment by kaitlynhair** [comment]
Good point Lukas. I have been working on some improvements in the v1 branch which will be merged shortly. I have now added a warning to notify users of what fields are missing and set missing fields to NA - coming in V1.0

**Comment by kaitlynhair** [comment]
Now added a menu to allow users to proceed (or not proceed) with dedup if key fields are missing and have documented requirements in readme.
